# HA-MONITOR-API

services:
    ha-monitor-api:
        container_name: ha-monitor-api
        image: igoramadas/ha-monitor-api:latest
        restart: always
        privileged: true

        # The network mode needs to be 'host' for us to get the right stats.
        network_mode: host

        # We need to map in the system items so that we can pull our stats from the underlying host OS.
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
